env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  indent: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
